### ISSUE TITLE
Background image loads late

### ISSUE THREAD

**Issue by SKBruck** [arsmentis/arsmentis-site#13]
Likely because it's in the css

**Comment by artlogic** [comment]
Here's an easy fix: https://serversideup.net/how-to-preload-css-background-images/

**Comment by SKBruck** [comment]
Duplicate of #23; closing

**Comment by artlogic** [comment]
Not a duplicate - #23 is a PR, not an issue.

**Comment by SKBruck** [comment]
Rolls into #24 - closing.

**Comment by artlogic** [comment]
Re-opening.
