### ISSUE TITLE
SVG logo doesn't display correctly on some browsers

### ISSUE THREAD

**Issue by SKBruck** [arsmentis/arsmentis-site#14]

**Comment by SKBruck** [comment]
Firefox is having rendering issues. Switching to png for now; will come back to this later.

**Comment by SKBruck** [comment]
Need to test again on Firefox to see if the bug is fixed

**Comment by SKBruck** [comment]
No longer able to replicate issue on firefox. Closing.

**Comment by artlogic** [comment]
The current site is using a png. Is that why you can't duplicate it?
