### ISSUE TITLE
Clients screen doesn't flow properly at tablet widths

### ISSUE THREAD

**Issue by artlogic** [arsmentis/arsmentis-site#20]
<img width="914" alt="Screen Shot 2020-09-14 at 8 02 18 PM" src="https://user-images.githubusercontent.com/137194/93149754-3405b180-f6c5-11ea-8924-d4d49c30d031.png">

**Comment by SKBruck** [comment]
Partial fix is to remove the `<row>` tags around the `<col>` tags (except the required initial `<row>`, and make sure the images have a `min-height` set. There's still a problem with the column content becoming misaligned that I'm trying to figure out with bootstrap's utilities.

Hopeful fix estimate: 11-21-2021

**Comment by SKBruck** [comment]
Site for testing 2 col layout: https://skbruck.github.io/tests/index.html

**Comment by artlogic** [comment]
Two column layout looks fine to me.
